import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "dashboard/dashboard1",
    title: "Inicio",
    iconType: "feather",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    roles: ["ADMIN", "EMPLE", "CONTA", "EMPRESA"],
    submenu: [],
    
  },
  {
    path: "tiendas",
    title: "Tienda",
    iconType: "feather",
    icon: "truck",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    roles: ["ADMIN", "EMPLE", "CONTA",  "EMPRESA"],
    submenu: [
      {
        path: "tiendas/tienda",
        title: "Tienda Solidaria",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        roles: ["ADMIN", "EMPLE", "EMPRESA"],
        submenu: [],
      },
      {
        path: "tiendas/productos",
        title: "Registro de Productos",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        roles: ["ADMIN", "EMPRESA"],
        submenu: [],
      },
    ],
  },
  {
    path: "ventas",
    title: "Ventas",
    iconType: "feather",
    icon: "credit-card",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    roles: ["ADMIN", "EMPLE", "EMPRESA"],
    submenu: [
      {
        path: "ventas/venta",
        title: "Registrar Venta",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        roles: ["ADMIN", "EMPLE"],
        submenu: [],
      },
      {
        path: "ventas/historial_venta",
        title: "Historial de Ventas",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        roles: ["ADMIN", "EMPLE"],
        submenu: [],
      },
      {
        path: "ventas/venta_empleado",
        title: "Ventas de Empleados",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        roles: ["ADMIN", "EMPRESA"],
        submenu: [],
      },
    ],
    
  },
  {
    path: "empleados",
    title: "Empleados",
    iconType: "feather",
    icon: "briefcase",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    roles: ["ADMIN", "EMPLE", "CONTA" ,"EMPRESA"],
    submenu: [
      {
        path: "empleados/empleado",
        title: "Empleados",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "1",
        badgeClass: "",
        roles: ["ADMIN", "CONTA", "EMPRESA"],
        submenu: [],
      },
      {
        path: "empleados/expediente",
        title: "Expediente de Empleados",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "1",
        badgeClass: "",
        roles: ["ADMIN", "CONTA",  "EMPRESA"],
        submenu: [],
      },
      {
        path: "empleados/empleado_desabilitado",
        title: "Empleados Desactivados",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "1",
        badgeClass: "",
        roles: ["ADMIN",  "EMPRESA"],
        submenu: [],
      },
    ],
  },
  {
    path: "salarios",
    title: "Contabilidad",
    iconType: "feather",
    icon: "dollar-sign",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    roles: ["ADMIN", "CONTA",  "EMPRESA"],
    submenu: [
      {
        path: "salarios/salario",
        title: "Pago de salarios",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "1",
        badgeClass: "",
        roles: ["ADMIN", "EMPRESA","CONTA"],
        submenu: [],
      },
      {
        path: "salarios/historial_salario",
        title: "Historial de Aumento de Salarios",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "1",
        badgeClass: "",
        roles: ["ADMIN", "EMPRESA"],
        submenu: [],
      },
    ]
  },
  {
    path: "usuario",
    title: "Usuarios",
    iconType: "feather",
    icon: "user",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    roles: ["ADMIN",  "EMPRESA"],
    submenu: [
      {
        path: "usuario/usuario",
        title: "Usuarios",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "1",
        badgeClass: "",
        roles: ["ADMIN", "EMPRESA"],
        submenu: [],
      },
      {
        path: "usuario/usuario_desabilitado",
        title: "Usuarios Deshabilitados",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "1",
        badgeClass: "",
        roles: ["ADMIN",  "EMPRESA"],
        submenu: [],
      },
    ],
  },

];
